---
- name: Ensure bitbucket.org is a known host
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.ssh/known_hosts"
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa bitbucket.org') }}"
    regexp: "^bitbucket\\.org"

- name: Clone laravel project
  git:
    repo: "{{ project_git }}"
    dest: /var/www/html/{{ work_dir }}
  when: ansible_distribution == 'Ubuntu'
