---
- name: Ensure supervisor installed
  homebrew:
    name: supervisor
    options: force
  register: supervisor_installed

- name: Create supervisor directory
  file:
    path: "/usr/local/etc/supervisor.d"
    state: directory
    mode: 0755
  become: false
  when: supervisor_installed.changed

- name: Copy supervisor config
  template: src=supervisord-macosx.conf.j2 dest=/usr/local/etc/supervisord.ini
  changed_when: false
  when: supervisor_installed.changed

- include: macosx-setup-horizon.yml
  when: horizon

- include: macosx-setup-mailcatcher.yml
  when: mailcatcher
