---
- name: Set project_path
  set_fact: project_path={{ ansible_env.HOME }}/{{ work_dir }}/{{ work_domain }}

- name: Clone laravel project
  git:
    repo: "{{ project_git }}"
    dest: "{{ project_path }}"
    version: "{{ project_git_branch }}"
    force: true
  environment:
    PATH: "{{ lookup('env','PATH') }}"

- name: Copy environment file
  copy:
    src: "{{ project_path }}/.env.local"
    dest: "{{ project_path }}/.env"
    mode: 0644
    remote_src: true

- name: Install pexpect
  pip:
    name:
      - pexpect
    executable: /usr/local/bin/pip3
  when: nfs_install

- name: Copy nfs script file
  copy:
    src: "files/nfs.sh"
    dest: "{{ project_path }}/sh/install/nfs-from-ansible.sh"
    mode: 0777
  when: nfs_install

- name: Run NFS configuration
  become: true
  become_user: "{{ ansible_user }}"
  expect:
    command: |
      bash -lc "cd {{ project_path }} \
      && sh/install/nfs-from-ansible.sh"
    responses:
      "Password:": "{{ ansible_pass }}"
    timeout: 90
  environment:
    PATH: "{{ lookup('env','PATH') }}"
  changed_when: false
  when: nfs_install

- name: Start services via docker-compose
  command: |
    bash -lc "cd {{ project_path }} \
    && docker-compose up -d"
  environment:
    PATH: "{{ lookup('env','PATH') }}"
  changed_when: false

- name: Copy docker deploy script file
  copy:
    src: "files/docker-macos.sh"
    dest: "{{ project_path }}/sh/install/docker-from-ansible.sh"
    mode: 0777

- name: Copy nginx script file
  copy:
    src: "files/nginx-macos.sh"
    dest: "{{ project_path }}/sh/install/nginx-from-ansible.sh"
    mode: 0777

- name: Run deploy dashboard script
  command: |
    bash -lc "cd {{ project_path }} \
    && sh/install/docker-from-ansible.sh"
  environment:
    PATH: "{{ lookup('env','PATH') }}"
  ignore_errors: true
  changed_when: false
  become: true

- name: Remove docker deploy script file
  ansible.builtin.file:
    path: "{{ project_path }}/sh/install/docker-from-ansible.sh"
    state: absent

- name: Remove nginx script file
  ansible.builtin.file:
    path: "{{ project_path }}/sh/install/nginx-from-ansible.sh"
    state: absent

- name: Remove nfs script file
  ansible.builtin.file:
    path: "{{ project_path }}/sh/install/nfs-from-ansible.sh"
    state: absent
  when: nfs_install

- name: Copy info file
  template:
    src: info.txt.j2
    dest: $HOME/Desktop/{{ work_domain }}.txt
    mode: 0777
