---
- name: Copy environment file
  copy:
    src: /var/www/html/{{ work_dir }}/.env.example
    dest: /var/www/html/{{ work_dir }}/.env
    remote_src: true

- name: Change APP_URL
  lineinfile:
    path: /var/www/html/{{ work_dir }}/.env
    regexp: '^APP_URL='
    line: 'APP_URL=https://{{ work_domain }}'

- name: Change database host
  lineinfile:
    path: /var/www/html/{{ work_dir }}/.env
    regexp: '^DB_HOST='
    line: 'DB_HOST={{ mysql_host }}'

- name: Change database user
  lineinfile:
    path: /var/www/html/{{ work_dir }}/.env
    regexp: '^DB_USERNAME='
    line: 'DB_USERNAME={{ mysql_user }}'

- name: Change database password
  lineinfile:
    path: /var/www/html/{{ work_dir }}/.env
    regexp: '^DB_PASSWORD='
    line: 'DB_PASSWORD={{ mysql_password }}'

- name: Change database name
  lineinfile:
    path: /var/www/html/{{ work_dir }}/.env
    regexp: '^DB_DATABASE='
    line: 'DB_DATABASE={{ mysql_database }}'

- name: Change s3 acccess key
  lineinfile:
    path: /var/www/html/{{ work_dir }}/.env
    regexp: '^S3_KEY='
    line: 'S3_KEY={{ s3_key }}'

- name: Change s3 secret key
  lineinfile:
    path: /var/www/html/{{ work_dir }}/.env
    regexp: '^S3_SECRET_KEY='
    line: 'S3_SECRET_KEY={{ s3_secret }}'

- name: Change s3 host
  lineinfile:
    path: /var/www/html/{{ work_dir }}/.env
    regexp: '^S3_AWS_URL='
    line: 'S3_AWS_URL={{ s3_host }}'

- name: Change s3 bucket
  lineinfile:
    path: /var/www/html/{{ work_dir }}/.env
    regexp: '^S3_BUCKET='
    line: 'S3_BUCKET={{ s3_bucket }}'

- name: Change s3 region
  lineinfile:
    path: /var/www/html/{{ work_dir }}/.env
    regexp: '^S3_REGION='
    line: 'S3_REGION={{ s3_region }}'

- name: Change s3 use endpoint
  lineinfile:
    path: /var/www/html/{{ work_dir }}/.env
    regexp: '^S3_USE_ENDPOINT='
    line: 'S3_USE_ENDPOINT=true'
