- name: Ensure ruby installed for mailcatcher
  apt:
    name: ruby-full
    update_cache: yes
    cache_valid_time: 86400
  become: true
  when: "mailcatcher == 'true'"

- name: Install mailcatcher
  gem:
    name: mailcatcher
    state: present
  become: true
  when: "mailcatcher == 'true'"

- name: Copy mailcatcher config
  template:
    src: "mailcatcher-ubuntu.conf.j2"
    dest: "/etc/supervisor/conf.d/mailcatcher.conf"
  become: true
  when: "mailcatcher == 'true'"
  notify: Restart Supervisor
