---
- name: Clone laravel project
  git:
    repo: "{{ project_git }}"
    dest: "{{ work_dir }}"
    version: "{{ project_git_branch }}"
    force: true
  environment:
    PATH: "{{ lookup('env','PATH') }}"

- name: Copy environment file
  copy:
    src: "{{ work_dir }}/.env.example"
    dest: "{{ work_dir }}/.env"
    mode: 0644
    remote_src: true

# yamllint disable
- name: Setup environment file
  lineinfile:
    path: "{{ item.path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    mode: 0644
  loop:
    - {path: '{{ work_dir }}/.env', regexp: '^DOCKER_MAILHOG_PORT=', line: 'DOCKER_MAILHOG_PORT={{ docker_mailhog_port }}'}
    - {path: '{{ work_dir }}/.env', regexp: '^DOCKER_MINIO_PORT=', line: 'DOCKER_MINIO_PORT={{ docker_minio_port }}'}
    - {path: '{{ work_dir }}/.env', regexp: '^DOCKER_MYSQL_PORT=', line: 'DOCKER_MYSQL_PORT={{ docker_mysql_port }}'}
    - {path: '{{ work_dir }}/.env', regexp: '^DOCKER_APP_PORT=', line: 'DOCKER_APP_PORT={{ docker_app_port }}'}
    - {path: '{{ work_dir }}/.env', regexp: '^DOCKER_SUPERVISOR_PORT=', line: 'DOCKER_SUPERVISOR_PORT={{ docker_supervisor_port }}'}
    - {path: '{{ work_dir }}/.env', regexp: '^DOCKER_SUPERVISOR_PORT_QUEUE=', line: 'DOCKER_SUPERVISOR_PORT_QUEUE={{ docker_supervisor_port_queue }}'}
# yamllint enable

- name: Start services via docker-compose
  command: |
    bash -lc "cd {{ work_dir }} \
    && docker-compose up -d"
  environment:
    PATH: "{{ lookup('env','PATH') }}"
  changed_when: false

- name: Copy docker deploy script file
  copy:
    src: "files/docker-ubuntu.sh"
    dest: "{{ work_dir }}/sh/install/docker-from-ansible.sh"
    mode: 0777

- name: Copy nginx script file
  copy:
    src: "files/nginx-ubuntu.sh"
    dest: "{{ work_dir }}/sh/install/nginx-from-ansible.sh"
    mode: 0777

- name: Run deploy dashboard script
  command: |
    bash -lc "cd {{ work_dir }} \
    && sh/install/docker-from-ansible.sh"
  environment:
    PATH: "{{ lookup('env','PATH') }}"
  ignore_errors: true
  changed_when: false
  become: true

- name: Ser permission to mysql log dir
  command: |
    bash -lc "cd {{ work_dir }} \
    && chmod -R 777 ../docker-data/{{ docker_app_name }}-log/mysql"
  environment:
    PATH: "{{ lookup('env','PATH') }}"
  ignore_errors: true
  changed_when: false
  become: true

- name: Restart mysql services via docker-compose
  command: |
    bash -lc "cd {{ work_dir }} \
    && docker-compose restart mysql"
  environment:
    PATH: "{{ lookup('env','PATH') }}"
  changed_when: false

- name: Remove docker deploy script file
  ansible.builtin.file:
    path: "{{ work_dir }}/sh/install/docker-from-ansible.sh"
    state: absent

- name: Remove nginx script file
  ansible.builtin.file:
    path: "{{ work_dir }}/sh/install/nginx-from-ansible.sh"
    state: absent
