---
name: Ansible Lint
on: [push, pull_request]    # yamllint disable-line rule:truthy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@151b9a2
        with:
          targets: "./"
          args: -x 106
